AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Dispatcher Service (PROD)

Parameters:
  QueueArn:
    Type: String

Resources:

  DispatcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dispatcher-prod
      CodeUri: ./src
      Handler: lambda_function.lambda_handler
      Runtime: python3.14
      MemorySize: 128
      Timeout: 5

      Environment:
        Variables:
          TELEGRAM_TOKEN: "8270938077:AAFWriotCwLm2m2k-X4mfhjC0nt_ABiC7gM"
          CHAT_ID: "-1003741912580"

      Policies:
        - SQSPollerPolicy:
            QueueName: !Select [5, !Split [":", !Ref QueueArn]]

      Events:
        SQS:
          Type: SQS
          Properties:
            Queue: !Ref QueueArn
            BatchSize: 10