AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Triage Service (PROD)

Resources:

  TicketsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TicketsTable-prod
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ticket_id
          AttributeType: S
      KeySchema:
        - AttributeName: ticket_id
          KeyType: HASH

  TicketQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: TicketQueue-prod

  TriageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: triage-engine-prod
      CodeUri: ./src
      Handler: lambda_function.lambda_handler
      Runtime: python3.14
      MemorySize: 128
      Timeout: 5

      Environment:
        Variables:
          TABLE_NAME: !Ref TicketsTable
          QUEUE_URL: !Ref TicketQueue

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TicketsTable
        - SQSSendMessagePolicy:
            QueueName: !GetAtt TicketQueue.QueueName

      Events:
        ApiTrigger:
          Type: HttpApi
          Properties:
            Path: /ticket
            Method: POST
            CorsConfiguration:
              AllowOrigins:
                - "*"
              AllowMethods:
                - POST
              AllowHeaders:
                - "*"

Outputs:
  ApiEndpoint:
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
  QueueArn:
    Value: !GetAtt TicketQueue.Arn